name: Luna HTML Fixer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (if applicable)
        uses: actions/setup-node@v3
        with:
          node-version: '14' # Use your required Node version

      - name: Install dependencies
        run: npm install # Adjust if you use a different package manager

      - name: Run Luna HTML Fixer
        run: npm run lint # Replace with the actual command for your fixer

      - name: Upload report
        if: failure() # Upload report if the previous step failed
        uses: actions/upload-artifact@v3
        with:
          name: luna-html-fixer-report
          path: path/to/report/file # Specify the path to your report file
